### ISSUE TITLE
OpenEHR Ruby Client

### ISSUE THREAD

**Issue by timcknowles** [Epidurio/epidur.io#13]
Ruby client library for openEHR to wrap the following functionality in an easy-to-use, object oriented layer, using Rubyish and Rails-esque idioms and conventions.

Basic

* handle process of authentication to the EtherCIS CDR
* handle HTTP(S) transactions automagically
* query the CDR for available templates
* expose a representation of these templates in the Ruby object-model, following Rails (ActiveRecord) ORM conventions for the API (where this is possible) so it is a fairly familiar interface for Ruby developers
* enable changes to these objects to be committed to the openEHR CDR as flat JSON (POST)
* simplify the transmission of AQL to the CDR (AQL is not at this stage auto-generated, one would need to create it manually for each transaction in a system such as the Marand tooling)

Intermediate

* calls to object getter methods result in autogeneration of correct AQL from introspection of the Ruby objects
* autovalidation of Ruby objects from the validation data in openEHR templates
* test compatibility of calls across Think!EHR and EtherCIS CDRs
* helper methods and convenience methods that make common queries easier, or group common sequences of queries
* command line tools for creating scaffolded UI from a selected template or archetype
* replace any important missing functionality in Rails that was lost by not using ActiveRecord (the main Rails ORM)

**Comment by pacharanero** [comment]
closing as this is now going to be implemented in Python
