### ISSUE TITLE
Convert Business logic to OPAL

### ISSUE THREAD

**Issue by timcknowles** [Epidurio/epidur.io#14]
consider using OPAL healthcare application framework.

Pros:

*Lot's of relevant reusable features. Save time by nor re-inventing the wheel.
*Proven real world implementations 

*Cons:

*Less diversity. nice to have ruby and python options in the future.
*Time savings may not be realised due to developer learning curve in switching from Rails to Django.

**Comment by davidmiller** [comment]
Hi @timcknowles !

I'd ask @fredkingham who was closer at Ideas Lab, but AFAICT the currently 'Business logic' part of Epidur.io is right in the middle of the sweet spot for Opal...
(You mean the bits that're in Rails right? ;) )

Ruby and Python are basically the same language once you step back a bit... but to be fair, the learning curve is a thing.
@pacharanero is in the process of converting and can probably speak to how hard he's found it ?

Suspect the Opal team would be keen to help...

Feel free to hit me up if you'd like to talk it through? 
david@openhealthcare.org.uk

**Comment by fredkingham** [comment]
@timcknowles hello!

From memory, I think opal can help (I would say that!).

We've done a bunch of stuff that's really similar before so we have the tooling where we can get you something that fulfils the existing functionality in less that a couple of hours.

I'd need to look at the FHIR stuff to make sure we can synch with that easily.

If you're around and fancy popping in to OHC HQ at some point, pop in and we'll see if we can jump start you.

**Comment by pacharanero** [comment]
It's an interesting discussion and there's no real 'right' answer.
Some thoughts I've had in both directions:
* Ruby is still a nicer language than Python, and all Rubyists are by definition cooler than Pythonists, and naturally better surfers.
* Django, however, does Models declaratively and it's WAY better than Rails' handmade migrations approach. The built-in Admin interface rocks.
* Almost everything else in Django has a more or less semantically identical equivalent in Rails and vice-versa, and the syntax although different, is not that hard to learn.
* I'm conscious that Tim is the originator and founder of this project and in the end I'd regard his decision as final as the BDFL. 
* Time pressure on delivery makes this decision a little harder - on one hand we have: learning curve to get Tim up and running on Opal + time to re-implement current functionality in Opal, vs: Carrying on in Ruby/Rails with existing codebase but knowing that we will need to manually redo some work that is 'out of the box' in Opal.
* I think @fredkingham is right: that it's not going to take very long in Opal to get to the point where we have comparable or better functionality in Opal: an EpiduralRequestedPatientList and an EpiduralCompletedPatientList plus the Pathways (forms) which would enable adding patients to those lists. (realistically I reckon a couple of days, taking time to teach @timcknowles Opal, and also I am slower than @fredkingham @davidmiller)
* @timcknowles and I are having a call next week to kick off the official project and we'll keep OHCUK informed.

**Comment by pacharanero** [comment]
In time, I'd love for there to be a parallel sister Rails implementation of Opal's healthcare app 'specialisations', and maybe this is part of a ling term goal... But it's not possible to be done in the time we have for Epidur.io.

**Comment by timcknowles** [comment]
Thanks very much @davidmiller @fredkingham as @pacharanero  says - this is the nub of it 

> learning curve to get Tim up and running on Opal + time to re-implement current functionality in Opal, vs: Carrying on in Ruby/Rails with existing codebase but knowing that we will need to manually redo some work that is 'out of the box' in Opal.

We will discuss next week and get back to you. Thanks again for offer of help in OPAL.

**Comment by pacharanero** [comment]
We've run a fairly successful trial of switching to Opal in the last week or so. I think that it's worked well enough to continue in Opal. @timcknowles it's your final call - can we close this issue?

**Comment by timcknowles** [comment]
Agree excellent progress being made in OPAL i'm ready to let go
